# SpringBoot
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

strategy:
  matrix:
    Aurora:
      MySqlName: 'rg-ww-cb-aurora-mysql01'
      CountryName: 'aurora'
    Russia:
      MySqlName: 'rg-ww-cb-russia-aurora'
      CountryName: 'russia'
    France:
      MySqlName: 'rg-ww-cb-france-aurora'
      CountryName: 'france'
    Switzerland:
      MySqlName: 'rg-ww-cb-norway-aurora'
      CountryName: 'norway'

pool:
  vmImage: 'ubuntu-16.04'
  name: Azure Pipelines
  demands: maven

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '
              Get-ChildItem -Recurse -Include *.properties;
              $text= Get-Content -Path "src/main/resources/application.properties";
              "Original- "+$text;
              $text=$text -replace "rg-ww-cb-aurora-mysql01","$(MySqlName)";
              "Replaced> "+$text;
              $text | Set-Content "src/main/resources/application.properties";
              $text= Get-Content -Path "src/main/resources/application.properties";
              "FileProperties- "+$text;
            '
      
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: spring-$(CountryName)-drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    artifactName: spring-$(CountryName)
  condition: succeededOrFailed()
